//HintName: RecoverableModule.LuauModule.g.cs
// <auto-generated/>
#nullable enable

public sealed partial class RecoverableModule : global::Darp.Luau.ILuauModule<global::RecoverableModule>
{
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Darp.Luau.Generator", "GeneratorVersion")]
    public static string ModuleName => "recoverable";
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Darp.Luau.Generator", "GeneratorVersion")]
    public void OnLoad(global::Darp.Luau.LuauState state, in global::Darp.Luau.LuauTable module)
    {
        using global::Darp.Luau.LuauFunction __var0 = state.CreateFunctionBuilder(args =>
        {
            if (!args.TryValidateArgumentCount(0, out string? error))
                return global::Darp.Luau.LuauReturn.Error(error);
            var returns = this.CreateField();
            return global::Darp.Luau.LuauReturn.Ok(returns);
        });
        module.Set("Field", __var0);
        using global::Darp.Luau.LuauFunction __var1 = state.CreateFunctionBuilder(args =>
        {
            if (!args.TryValidateArgumentCount(0, out string? error))
                return global::Darp.Luau.LuauReturn.Error(error);
            var returns = this.DuplicateOne();
            return global::Darp.Luau.LuauReturn.Ok(returns);
        });
        module.Set("duplicate", __var1);
        using global::Darp.Luau.LuauFunction __var2 = state.CreateFunctionBuilder(args =>
        {
            if (!args.TryValidateArgumentCount(0, out string? error))
                return global::Darp.Luau.LuauReturn.Error(error);
            var returns = this.Ok();
            return global::Darp.Luau.LuauReturn.Ok(returns);
        });
        module.Set("ok", __var2);
    }
}
