//HintName: CollisionModule.LuauModule.g.cs
// <auto-generated/>
#nullable enable

public static partial class CollisionModule
{
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Darp.Luau.Generator", "GeneratorVersion")]
    public static string ModuleName => "collisions";
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Darp.Luau.Generator", "GeneratorVersion")]
    public static void OnLoad(global::Darp.Luau.LuauState state, in global::Darp.Luau.LuauTable module)
    {
        using global::Darp.Luau.LuauFunction __var0 = state.CreateFunctionBuilder(args =>
        {
            if (!args.TryValidateArgumentCount(0, out string? error))
                return global::Darp.Luau.LuauReturn.Error(error);
            var returns = global::CollisionModule.returns();
            return global::Darp.Luau.LuauReturn.Ok(returns);
        });
        module.Set("returns", __var0);
    }
}
