//HintName: ArcadeModule.LuauModule.g.cs
// <auto-generated/>
#nullable enable

public static partial class ArcadeModule
{
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Darp.Luau.Generator", "GeneratorVersion")]
    public static string ModuleName => "arcade";
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Darp.Luau.Generator", "GeneratorVersion")]
    public static void OnLoad(global::Darp.Luau.LuauState state, in global::Darp.Luau.LuauTable module)
    {
        using global::Darp.Luau.LuauFunction __var0 = state.CreateFunctionBuilder(args =>
        {
            if (!args.TryValidateArgumentCount(2, out string? error))
                return global::Darp.Luau.LuauReturn.Error(error);
            if (!args.TryReadNumber(parameterIndex: 1, out double a1Raw, out error))
                return global::Darp.Luau.LuauReturn.Error(error);
            int a1 = (int)a1Raw;
            if (!args.TryReadNumber(parameterIndex: 2, out double a2Raw, out error))
                return global::Darp.Luau.LuauReturn.Error(error);
            int a2 = (int)a2Raw;
            var returns = global::ArcadeModule.AddScore(a1, a2);
            return global::Darp.Luau.LuauReturn.Ok(returns);
        });
        module.Set("add_score", __var0);
        module.Set("difficulty", (double)Difficulty);
        module.Set("tokens", Tokens);
    }
}
