//HintName: GuildModule.LuauModule.g.cs
// <auto-generated/>
#nullable enable

public sealed partial class GuildModule : global::Darp.Luau.ILuauModule<global::GuildModule>
{
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Darp.Luau.Generator", "GeneratorVersion")]
    public static string ModuleName => "guild";
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Darp.Luau.Generator", "GeneratorVersion")]
    public void OnLoad(global::Darp.Luau.LuauState state, in global::Darp.Luau.LuauTable module)
    {
        using global::Darp.Luau.LuauTable __var0 = state.CreateTable();
        using global::Darp.Luau.LuauFunction __var1 = state.CreateFunctionBuilder(args =>
        {
            if (!args.TryValidateArgumentCount(1, out string? error))
                return global::Darp.Luau.LuauReturn.Error(error);
            if (!args.TryReadUtf8String(parameterIndex: 1, out global::System.ReadOnlySpan<byte> a1Raw, out error))
                return global::Darp.Luau.LuauReturn.Error(error);
            string a1 = global::System.Text.Encoding.UTF8.GetString(a1Raw);
            var returns = this.CreateHero(a1);
            return global::Darp.Luau.LuauReturn.Ok(global::Darp.Luau.IntoLuau.FromUserdata(returns));
        });
        __var0.Set("create", __var1);
        module.Set("heroes", __var0);
        
    }
}
