//HintName: DemoModule.LuauModule.g.cs
// <auto-generated/>
#nullable enable

public static partial class DemoModule
{
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Darp.Luau.Generator", "GeneratorVersion")]
    public static string ModuleName => "demo";
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Darp.Luau.Generator", "GeneratorVersion")]
    public static void OnLoad(global::Darp.Luau.LuauState state, in global::Darp.Luau.LuauTable module)
    {
        using global::Darp.Luau.LuauTable __var0 = state.CreateTable();
        using global::Darp.Luau.LuauFunction __var1 = state.CreateFunctionBuilder(args =>
        {
            if (!args.TryValidateArgumentCount(0, out string? error))
                return global::Darp.Luau.LuauReturn.Error(error);
            var returns = global::DemoModule.One();
            return global::Darp.Luau.LuauReturn.Ok(returns);
        });
        __var0.Set("b_c", __var1);
        module.Set("a", __var0);
        
        using global::Darp.Luau.LuauTable __var2 = state.CreateTable();
        using global::Darp.Luau.LuauFunction __var3 = state.CreateFunctionBuilder(args =>
        {
            if (!args.TryValidateArgumentCount(0, out string? error))
                return global::Darp.Luau.LuauReturn.Error(error);
            var returns = global::DemoModule.Two();
            return global::Darp.Luau.LuauReturn.Ok(returns);
        });
        __var2.Set("c", __var3);
        module.Set("a_b", __var2);
        
        using global::Darp.Luau.LuauFunction __var4 = state.CreateFunctionBuilder(args =>
        {
            if (!args.TryValidateArgumentCount(0, out string? error))
                return global::Darp.Luau.LuauReturn.Error(error);
            var returns = global::DemoModule.FooBar();
            return global::Darp.Luau.LuauReturn.Ok(returns);
        });
        module.Set("foo-bar", __var4);
        using global::Darp.Luau.LuauTable __var5 = state.CreateTable();
        using global::Darp.Luau.LuauFunction __var6 = state.CreateFunctionBuilder(args =>
        {
            if (!args.TryValidateArgumentCount(0, out string? error))
                return global::Darp.Luau.LuauReturn.Error(error);
            var returns = global::DemoModule.CreateItem();
            return global::Darp.Luau.LuauReturn.Ok(returns);
        });
        __var5.Set("create item", __var6);
        module.Set("tools", __var5);
        
    }
}
