using System.CodeDom.Compiler;

namespace Darp.Luau.Generator.GeneratedExports;

internal static class ExportEmitterHelper
{
    public static void WriteFileHeader(IndentedTextWriter writer)
    {
        writer.WriteLine("// <auto-generated/>");
        writer.WriteLine("#nullable enable");
        writer.WriteLine();
    }

    public static bool WriteNamespaceStart(IndentedTextWriter writer, string? namespaceName)
    {
        if (string.IsNullOrWhiteSpace(namespaceName))
            return false;

        writer.WriteLine($"namespace {namespaceName}");
        writer.WriteLine("{");
        writer.Indent++;
        return true;
    }

    public static void WriteNamespaceEnd(IndentedTextWriter writer, bool hasNamespace)
    {
        if (!hasNamespace)
            return;

        writer.Indent--;
        writer.WriteLine("}");
    }

    public static string WithBaseList(string typeDeclaration, string? baseList)
    {
        return string.IsNullOrWhiteSpace(baseList) ? typeDeclaration : $"{typeDeclaration} : {baseList}";
    }

    public sealed class LocalNameAllocator
    {
        private int _next;

        public string Next() => $"__var{_next++}";
    }
}
