using System.CodeDom.Compiler;
using System.Diagnostics.CodeAnalysis;
using System.Globalization;
using System.Text;
using Darp.Luau.Generator.Helpers;
using Microsoft.CodeAnalysis.CSharp;
using static Darp.Luau.Generator.Helpers.EmitterHelper;

namespace Darp.Luau.Generator.CreateFunction;

internal static class CreateFunctionEmitter
{
    public static string GetHintName(CreateFunctionModel model)
    {
        string key = $"{model.Location.Version}:{model.Location.Data}:{GetFunctionRepresentation(model.Signature)}";
        return $"Darp.Luau.LuauState.CreateFunctionInterceptors.{ComputeStableHash(key)}.g.cs";
    }

    public static bool TryEmit(CreateFunctionModel model, [NotNullWhen(true)] out string? source)
    {
        using var stringWriter = new StringWriter();
        using var writer = new IndentedTextWriter(stringWriter);

        InteropSignature signature = model.Signature;
        string callFunction = GetFunctionRepresentation(signature);
        string opt = string.Join("", signature.Parameters.Select((x, i) => x.IsNullable ? $"Opt{i + 1}" : ""));
        string optReturn = string.Join("", signature.ReturnTypes.Select((x, i) => x.IsNullable ? $"OptR{i + 1}" : ""));
        string locationData = SymbolDisplay.FormatLiteral(model.Location.Data, quote: true);

        writer.WriteMultiLine(
            $$"""
            // <auto-generated/>
            #nullable enable

            namespace Darp.Luau.Generator
            {
            file static class CreateFunctionInterceptors
            {
                [global::System.Runtime.CompilerServices.InterceptsLocationAttribute({{model.Location.Version}}, {{locationData}})]
                public static global::Darp.Luau.LuauFunction CreateMethod{{opt}}{{optReturn}}(this global::Darp.Luau.LuauState state, {{callFunction}} onLuaCall)
                {
                    global::System.ArgumentNullException.ThrowIfNull(state);
                    global::System.ArgumentNullException.ThrowIfNull(onLuaCall);
                    return state.CreateFunctionBuilder(F);

            """
        );
        writer.Indent = 2;
        WriteFunctionBody(writer, signature);
        writer.Indent = 1;
        writer.WriteLine("}");
        writer.Indent = 0;
        writer.WriteMultiLine(
            """
            }
            }

            namespace System.Runtime.CompilerServices
            {
                [global::System.Diagnostics.Conditional("DEBUG")]
                [AttributeUsage(AttributeTargets.Method, AllowMultiple = true)]
                file sealed class InterceptsLocationAttribute : Attribute
                {
                    public InterceptsLocationAttribute(int version, string data)
                    {
                        _ = version;
                        _ = data;
                    }
                }
            }
            """
        );
        source = stringWriter.ToString();
        return true;
    }

    private static void WriteFunctionBody(IndentedTextWriter writer, InteropSignature signature)
    {
        string[] paramExtractions = signature
            .Parameters.Select((paramType, i) => LuauMarshalEmitter.GenerateParameterRead(i + 1, paramType))
            .ToArray();

        string callExpression =
            $"onLuaCall({string.Join(", ", Enumerable.Range(1, paramExtractions.Length).Select(i => $"a{i}"))})";

        writer.WriteLine("global::Darp.Luau.LuauReturn F(global::Darp.Luau.LuauArgs args)");
        writer.WriteLine("{");
        writer.Indent++;
        writer.WriteLine($"if (!args.TryValidateArgumentCount({signature.Parameters.Length}, out string? error))");
        writer.WriteLine("    return global::Darp.Luau.LuauReturn.Error(error);");
        writer.WriteMultiLine(string.Join("\n", paramExtractions));
        if (signature.ReturnTypes.Length == 0)
        {
            writer.WriteLine($"{callExpression};");
            writer.WriteLine("return global::Darp.Luau.LuauReturn.Ok();");
        }
        else
        {
            writer.WriteLine($"var returns = {callExpression};");
            if (signature.ReturnTypes.Length == 1)
            {
                writer.WriteLine(
                    $"return global::Darp.Luau.LuauReturn.Ok({LuauMarshalEmitter.FormatIntoLuauExpression("returns", signature.ReturnTypes[0])});"
                );
            }
            else
            {
                writer.WriteLine(
                    $"return global::Darp.Luau.LuauReturn.Ok({string.Join(", ", signature.ReturnTypes.Select((x, i) => LuauMarshalEmitter.FormatIntoLuauExpression($"returns.Item{i + 1}", x)))});"
                );
            }
        }
        writer.Indent--;
        writer.WriteLine("}");
    }

    private static string ComputeStableHash(string value)
    {
        const ulong offset = 14695981039346656037UL;
        const ulong prime = 1099511628211UL;
        ulong hash = offset;
        foreach (byte b in Encoding.UTF8.GetBytes(value))
        {
            hash ^= b;
            hash *= prime;
        }
        return hash.ToString("x16", CultureInfo.InvariantCulture);
    }
}
