//HintName: Darp.Luau.LuauState.CreateFunctionInterceptors.g.cs
// <auto-generated/>
#nullable enable

namespace Darp.Luau.Generator
{
file static class CreateFunctionInterceptors
{
    [global::System.Runtime.CompilerServices.InterceptsLocationAttribute(1, "FPJ6qx5kWZJzrxjGkG4BLnMAAAA=")]
    public static global::Darp.Luau.LuauFunction CreateMethod(this global::Darp.Luau.LuauState state, global::System.Action<global::Darp.Luau.LuauValue> onLuaCall)
    {
        global::System.ArgumentNullException.ThrowIfNull(state);
        global::System.ArgumentNullException.ThrowIfNull(onLuaCall);
        return state.CreateFunctionBuilder(F);

        global::Darp.Luau.LuauReturn F(global::Darp.Luau.LuauArgs args)
        {
            if (!args.TryValidateArgumentCount(1, out string? error))
                return global::Darp.Luau.LuauReturn.Error(error);
            if (!args.TryReadLuauValue(parameterIndex: 1, out global::Darp.Luau.LuauValue a1, out error))
                return global::Darp.Luau.LuauReturn.Error(error);
            onLuaCall(a1);
            return global::Darp.Luau.LuauReturn.Ok();
        }
    }
    [global::System.Runtime.CompilerServices.InterceptsLocationAttribute(1, "FPJ6qx5kWZJzrxjGkG4BLqcAAAA=")]
    public static global::Darp.Luau.LuauFunction CreateMethod(this global::Darp.Luau.LuauState state, global::System.Action<global::Darp.Luau.LuauTable,global::Darp.Luau.LuauString,global::Darp.Luau.LuauFunction> onLuaCall)
    {
        global::System.ArgumentNullException.ThrowIfNull(state);
        global::System.ArgumentNullException.ThrowIfNull(onLuaCall);
        return state.CreateFunctionBuilder(F);

        global::Darp.Luau.LuauReturn F(global::Darp.Luau.LuauArgs args)
        {
            if (!args.TryValidateArgumentCount(3, out string? error))
                return global::Darp.Luau.LuauReturn.Error(error);
            if (!args.TryReadLuauTable(parameterIndex: 1, out global::Darp.Luau.LuauTable a1, out error))
                return global::Darp.Luau.LuauReturn.Error(error);
            if (!args.TryReadLuauString(parameterIndex: 2, out global::Darp.Luau.LuauString a2, out error))
                return global::Darp.Luau.LuauReturn.Error(error);
            if (!args.TryReadLuauFunction(parameterIndex: 3, out global::Darp.Luau.LuauFunction a3, out error))
                return global::Darp.Luau.LuauReturn.Error(error);
            onLuaCall(a1, a2, a3);
            return global::Darp.Luau.LuauReturn.Ok();
        }
    }
}
}

namespace System.Runtime.CompilerServices
{
    [global::System.Diagnostics.Conditional("DEBUG")]
    [AttributeUsage(AttributeTargets.Method, AllowMultiple = true)]
    file sealed class InterceptsLocationAttribute : Attribute
    {
        public InterceptsLocationAttribute(int version, string data)
        {
            _ = version;
            _ = data;
        }
    }
}
