//HintName: Darp.Luau.LuauState.CreateFunctionInterceptors.ecdd40e2ac8def0f.g.cs
// <auto-generated/>
#nullable enable

namespace Darp.Luau.Generator
{
file static class CreateFunctionInterceptors
{
    [global::System.Runtime.CompilerServices.InterceptsLocationAttribute(1, "ScrubbedInterceptLocation")]
    public static global::Darp.Luau.LuauFunction CreateMethod(this global::Darp.Luau.LuauState state, global::System.Func<decimal,decimal, (decimal x1, decimal x2)> onLuaCall)
    {
        global::System.ArgumentNullException.ThrowIfNull(state);
        global::System.ArgumentNullException.ThrowIfNull(onLuaCall);
        return state.CreateFunctionBuilder(F);

        global::Darp.Luau.LuauReturn F(global::Darp.Luau.LuauArgs args)
        {
            if (!args.TryValidateArgumentCount(2, out string? error))
                return global::Darp.Luau.LuauReturn.Error(error);
            if (!args.TryReadNumber(parameterIndex: 1, out double a1Raw, out error))
                return global::Darp.Luau.LuauReturn.Error(error);
            decimal a1 = (decimal)a1Raw;
            if (!args.TryReadNumber(parameterIndex: 2, out double a2Raw, out error))
                return global::Darp.Luau.LuauReturn.Error(error);
            decimal a2 = (decimal)a2Raw;
            var returns = onLuaCall(a1, a2);
            return global::Darp.Luau.LuauReturn.Ok((double)returns.Item1, (double)returns.Item2);
        }
    }
}
}

namespace System.Runtime.CompilerServices
{
    [global::System.Diagnostics.Conditional("DEBUG")]
    [AttributeUsage(AttributeTargets.Method, AllowMultiple = true)]
    file sealed class InterceptsLocationAttribute : Attribute
    {
        public InterceptsLocationAttribute(int version, string data)
        {
            _ = version;
            _ = data;
        }
    }
}
