//HintName: Darp.Luau.LuauState.CreateFunctionInterceptors.g.cs
// <auto-generated/>
#nullable enable

namespace Darp.Luau.Generator
{
file static class CreateFunctionInterceptors
{
    [global::System.Runtime.CompilerServices.InterceptsLocationAttribute(1, "WLD29+zBcnR8Vgakn7ptf6cAAAA=")]
    [global::System.Runtime.CompilerServices.InterceptsLocationAttribute(1, "WLD29+zBcnR8Vgakn7ptf+cAAAA=")]
    public static global::Darp.Luau.LuauFunction CreateMethodOpt1OptR1(this global::Darp.Luau.LuauState state, global::System.Func<string?, string?> onLuaCall)
    {
        global::System.ArgumentNullException.ThrowIfNull(state);
        global::System.ArgumentNullException.ThrowIfNull(onLuaCall);
        return state.CreateFunctionBuilder(F);

        void F(ref LuauFunctions x)
        {
            global::System.ArgumentOutOfRangeException.ThrowIfNotEqual(x.NumberOfParameters, 1);
            global::System.ReadOnlySpan<byte> v1Lua = x.CheckStringOrNil(parameterIndex: 1, out bool v1IsNull);
            string? v1 = v1IsNull ? null : global::System.Text.Encoding.UTF8.GetString(v1Lua);
            var returns = onLuaCall(v1);
            x.ReturnParameter(returns);
        }
    }
    [global::System.Runtime.CompilerServices.InterceptsLocationAttribute(1, "WLD29+zBcnR8Vgakn7ptfzoBAAA=")]
    public static global::Darp.Luau.LuauFunction CreateMethod(this global::Darp.Luau.LuauState state, global::System.Func<string, string> onLuaCall)
    {
        global::System.ArgumentNullException.ThrowIfNull(state);
        global::System.ArgumentNullException.ThrowIfNull(onLuaCall);
        return state.CreateFunctionBuilder(F);

        void F(ref LuauFunctions x)
        {
            global::System.ArgumentOutOfRangeException.ThrowIfNotEqual(x.NumberOfParameters, 1);
            global::System.ReadOnlySpan<byte> v1Lua = x.CheckString(parameterIndex: 1);
            string v1 = global::System.Text.Encoding.UTF8.GetString(v1Lua);
            var returns = onLuaCall(v1);
            x.ReturnParameter(returns);
        }
    }
}
}

namespace System.Runtime.CompilerServices
{
    [global::System.Diagnostics.Conditional("DEBUG")]
    [AttributeUsage(AttributeTargets.Method, AllowMultiple = true)]
    file sealed class InterceptsLocationAttribute : Attribute
    {
        public InterceptsLocationAttribute(int version, string data)
        {
            _ = version;
            _ = data;
        }
    }
}
