//HintName: Darp.Luau.LuauState.CreateFunctionInterceptors.g.cs
// <auto-generated/>
#nullable enable

namespace Darp.Luau.Generator
{
file static class CreateFunctionInterceptors
{
    [global::System.Runtime.CompilerServices.InterceptsLocationAttribute(1, "ScrubbedInterceptLocation")]
    public static global::Darp.Luau.LuauFunction CreateMethod(this global::Darp.Luau.LuauState state, global::System.Action<global::System.ReadOnlySpan<char>> onLuaCall)
    {
        global::System.ArgumentNullException.ThrowIfNull(state);
        global::System.ArgumentNullException.ThrowIfNull(onLuaCall);
        return state.CreateFunctionBuilder(F);

        global::Darp.Luau.LuauReturn F(global::Darp.Luau.LuauArgs args)
        {
            if (!args.TryValidateArgumentCount(1, out string? error))
                return global::Darp.Luau.LuauReturn.Error(error);
            if (!args.TryReadUtf8String(parameterIndex: 1, out global::System.ReadOnlySpan<byte> a1Raw, out error))
                return global::Darp.Luau.LuauReturn.Error(error);
            global::System.Span<char> a1 = stackalloc char[global::System.Text.Encoding.UTF8.GetCharCount(a1Raw)];
            _ = global::System.Text.Encoding.UTF8.GetChars(a1Raw, a1);
            onLuaCall(a1);
            return global::Darp.Luau.LuauReturn.Ok();
        }
    }
}
}

namespace System.Runtime.CompilerServices
{
    [global::System.Diagnostics.Conditional("DEBUG")]
    [AttributeUsage(AttributeTargets.Method, AllowMultiple = true)]
    file sealed class InterceptsLocationAttribute : Attribute
    {
        public InterceptsLocationAttribute(int version, string data)
        {
            _ = version;
            _ = data;
        }
    }
}
