//HintName: Darp.Luau.LuauState.CreateFunctionInterceptors.g.cs
// <auto-generated/>
#nullable enable

namespace Darp.Luau.Generator
{
file static class CreateFunctionInterceptors
{
    [global::System.Runtime.CompilerServices.InterceptsLocationAttribute(1, "FPJ6qx5kWZJzrxjGkG4BLnMAAAA=")]
    public static global::Darp.Luau.LuauFunction CreateMethod(this global::Darp.Luau.LuauState state, global::System.Action<global::Darp.Luau.LuauValue> onLuaCall)
    {
        global::System.ArgumentNullException.ThrowIfNull(state);
        global::System.ArgumentNullException.ThrowIfNull(onLuaCall);
        return state.CreateFunctionBuilder(F);

        void F(ref LuauFunctions x)
        {
            global::System.ArgumentOutOfRangeException.ThrowIfNotEqual(x.NumberOfParameters, 1);
            global::Darp.Luau.LuauValue v1 = x.CheckLuauValue(parameterIndex: 1);
            onLuaCall(v1);
        }
    }
    [global::System.Runtime.CompilerServices.InterceptsLocationAttribute(1, "FPJ6qx5kWZJzrxjGkG4BLqcAAAA=")]
    public static global::Darp.Luau.LuauFunction CreateMethod(this global::Darp.Luau.LuauState state, global::System.Action<global::Darp.Luau.LuauTable,global::Darp.Luau.LuauString,global::Darp.Luau.LuauFunction> onLuaCall)
    {
        global::System.ArgumentNullException.ThrowIfNull(state);
        global::System.ArgumentNullException.ThrowIfNull(onLuaCall);
        return state.CreateFunctionBuilder(F);

        void F(ref LuauFunctions x)
        {
            global::System.ArgumentOutOfRangeException.ThrowIfNotEqual(x.NumberOfParameters, 3);
            global::Darp.Luau.LuauTable v1 = x.CheckLuauTable(parameterIndex: 1);
            global::Darp.Luau.LuauString v2 = x.CheckLuauString(parameterIndex: 2);
            global::Darp.Luau.LuauFunction v3 = x.CheckLuauFunction(parameterIndex: 3);
            onLuaCall(v1, v2, v3);
        }
    }
}
}

namespace System.Runtime.CompilerServices
{
    [global::System.Diagnostics.Conditional("DEBUG")]
    [AttributeUsage(AttributeTargets.Method, AllowMultiple = true)]
    file sealed class InterceptsLocationAttribute : Attribute
    {
        public InterceptsLocationAttribute(int version, string data)
        {
            _ = version;
            _ = data;
        }
    }
}
