//HintName: Darp.Luau.LuauState.CreateFunctionInterceptors.g.cs
// <auto-generated/>
#nullable enable

namespace Darp.Luau.Generator
{
file static class CreateFunctionInterceptors
{
    [global::System.Runtime.CompilerServices.InterceptsLocationAttribute(1, "gXe7H6FQOmtMXBD/GevKlnMAAAA=")]
    public static global::Darp.Luau.LuauFunction CreateMethod(this global::Darp.Luau.LuauState state, global::System.Action<double> onLuaCall)
    {
        global::System.ArgumentNullException.ThrowIfNull(state);
        global::System.ArgumentNullException.ThrowIfNull(onLuaCall);
        return state.CreateFunctionBuilder(F);

        void F(ref LuauFunctions x)
        {
            global::System.ArgumentOutOfRangeException.ThrowIfNotEqual(x.NumberOfParameters, 1);
            double v1 = x.CheckNumber(parameterIndex: 1);
            onLuaCall(v1);
        }
    }
    [global::System.Runtime.CompilerServices.InterceptsLocationAttribute(1, "gXe7H6FQOmtMXBD/GevKlqQAAAA=")]
    public static global::Darp.Luau.LuauFunction CreateMethod(this global::Darp.Luau.LuauState state, global::System.Action<int> onLuaCall)
    {
        global::System.ArgumentNullException.ThrowIfNull(state);
        global::System.ArgumentNullException.ThrowIfNull(onLuaCall);
        return state.CreateFunctionBuilder(F);

        void F(ref LuauFunctions x)
        {
            global::System.ArgumentOutOfRangeException.ThrowIfNotEqual(x.NumberOfParameters, 1);
            double v1Lua = x.CheckNumber(parameterIndex: 1);
            int v1 = (int)v1Lua;
            onLuaCall(v1);
        }
    }
}
}

namespace System.Runtime.CompilerServices
{
    [global::System.Diagnostics.Conditional("DEBUG")]
    [AttributeUsage(AttributeTargets.Method, AllowMultiple = true)]
    file sealed class InterceptsLocationAttribute : Attribute
    {
        public InterceptsLocationAttribute(int version, string data)
        {
            _ = version;
            _ = data;
        }
    }
}
