//HintName: Darp.Luau.LuauState.CreateFunctionInterceptors.g.cs
// <auto-generated/>
#nullable enable

namespace Darp.Luau.Generator
{
file static class CreateFunctionInterceptors
{
    [global::System.Runtime.CompilerServices.InterceptsLocationAttribute(1, "ug+W/e8jS/vg5AUQXlREwogAAAA=")]
    public static global::Darp.Luau.LuauFunction CreateMethod(this global::Darp.Luau.LuauState state, global::System.Func<global::MyEnum, global::MyEnum> onLuaCall)
    {
        global::System.ArgumentNullException.ThrowIfNull(state);
        global::System.ArgumentNullException.ThrowIfNull(onLuaCall);
        return state.CreateFunctionBuilder(F);

        void F(ref LuauFunctions x)
        {
            global::System.ArgumentOutOfRangeException.ThrowIfNotEqual(x.NumberOfParameters, 1);
            double v1Lua = x.CheckNumber(parameterIndex: 1);
            global::MyEnum v1 = (global::MyEnum)v1Lua;
            var returns = onLuaCall(v1);
            x.ReturnParameter((double)returns);
        }
    }
    [global::System.Runtime.CompilerServices.InterceptsLocationAttribute(1, "ug+W/e8jS/vg5AUQXlREwrkAAAA=")]
    public static global::Darp.Luau.LuauFunction CreateMethodOpt1OptR1(this global::Darp.Luau.LuauState state, global::System.Func<global::MyEnum?, global::MyEnum?> onLuaCall)
    {
        global::System.ArgumentNullException.ThrowIfNull(state);
        global::System.ArgumentNullException.ThrowIfNull(onLuaCall);
        return state.CreateFunctionBuilder(F);

        void F(ref LuauFunctions x)
        {
            global::System.ArgumentOutOfRangeException.ThrowIfNotEqual(x.NumberOfParameters, 1);
            double? v1Lua = x.CheckNumberOrNil(parameterIndex: 1);
            global::MyEnum? v1 = v1Lua.HasValue ? (global::MyEnum)v1Lua.Value : null;
            var returns = onLuaCall(v1);
            x.ReturnParameter((double?)returns);
        }
    }
}
}

namespace System.Runtime.CompilerServices
{
    [global::System.Diagnostics.Conditional("DEBUG")]
    [AttributeUsage(AttributeTargets.Method, AllowMultiple = true)]
    file sealed class InterceptsLocationAttribute : Attribute
    {
        public InterceptsLocationAttribute(int version, string data)
        {
            _ = version;
            _ = data;
        }
    }
}
