//HintName: Darp.Luau.LuauState.CreateFunctionInterceptors.g.cs
// <auto-generated/>
#nullable enable

namespace Darp.Luau.Generator
{
file static class CreateFunctionInterceptors
{
    [global::System.Runtime.CompilerServices.InterceptsLocationAttribute(1, "6TNgYwlHwcOmN8AoDRIclnMAAAA=")]
    public static global::Darp.Luau.LuauFunction CreateMethod(this global::Darp.Luau.LuauState state, global::System.Action<string> onLuaCall)
    {
        global::System.ArgumentNullException.ThrowIfNull(state);
        global::System.ArgumentNullException.ThrowIfNull(onLuaCall);
        return state.CreateFunctionBuilder(F);

        void F(ref LuauFunctions x)
        {
            global::System.ArgumentOutOfRangeException.ThrowIfNotEqual(x.NumberOfParameters, 1);
            global::System.ReadOnlySpan<byte> v1Lua = x.CheckString(parameterIndex: 1);
            string v1 = global::System.Text.Encoding.UTF8.GetString(v1Lua);
            onLuaCall(v1);
        }
    }
    [global::System.Runtime.CompilerServices.InterceptsLocationAttribute(1, "6TNgYwlHwcOmN8AoDRIclqQAAAA=")]
    [global::System.Runtime.CompilerServices.InterceptsLocationAttribute(1, "6TNgYwlHwcOmN8AoDRIcluAAAAA=")]
    public static global::Darp.Luau.LuauFunction CreateMethod(this global::Darp.Luau.LuauState state, global::System.Action<string,string> onLuaCall)
    {
        global::System.ArgumentNullException.ThrowIfNull(state);
        global::System.ArgumentNullException.ThrowIfNull(onLuaCall);
        return state.CreateFunctionBuilder(F);

        void F(ref LuauFunctions x)
        {
            global::System.ArgumentOutOfRangeException.ThrowIfNotEqual(x.NumberOfParameters, 2);
            global::System.ReadOnlySpan<byte> v1Lua = x.CheckString(parameterIndex: 1);
            string v1 = global::System.Text.Encoding.UTF8.GetString(v1Lua);
            global::System.ReadOnlySpan<byte> v2Lua = x.CheckString(parameterIndex: 2);
            string v2 = global::System.Text.Encoding.UTF8.GetString(v2Lua);
            onLuaCall(v1, v2);
        }
    }
}
}

namespace System.Runtime.CompilerServices
{
    [global::System.Diagnostics.Conditional("DEBUG")]
    [AttributeUsage(AttributeTargets.Method, AllowMultiple = true)]
    file sealed class InterceptsLocationAttribute : Attribute
    {
        public InterceptsLocationAttribute(int version, string data)
        {
            _ = version;
            _ = data;
        }
    }
}
