//HintName: Darp.Luau.LuauState.CreateFunctionInterceptors.g.cs
// <auto-generated/>
#nullable enable

namespace Darp.Luau.Generator
{
file static class CreateFunctionInterceptors
{
    [global::System.Runtime.CompilerServices.InterceptsLocationAttribute(1, "ScrubbedInterceptLocation")]
    public static global::Darp.Luau.LuauFunction CreateMethod(this global::Darp.Luau.LuauState state, global::System.Func<int> onLuaCall)
    {
        global::System.ArgumentNullException.ThrowIfNull(state);
        global::System.ArgumentNullException.ThrowIfNull(onLuaCall);
        return state.CreateFunctionBuilder(F);

        global::Darp.Luau.LuauReturn F(global::Darp.Luau.LuauArgs args)
        {
            if (!args.TryValidateArgumentCount(0, out string? error))
                return global::Darp.Luau.LuauReturn.Error(error);

            var returns = onLuaCall();
            return global::Darp.Luau.LuauReturn.Ok(returns);
        }
    }
    [global::System.Runtime.CompilerServices.InterceptsLocationAttribute(1, "ScrubbedInterceptLocation")]
    public static global::Darp.Luau.LuauFunction CreateMethod(this global::Darp.Luau.LuauState state, global::System.Func<string> onLuaCall)
    {
        global::System.ArgumentNullException.ThrowIfNull(state);
        global::System.ArgumentNullException.ThrowIfNull(onLuaCall);
        return state.CreateFunctionBuilder(F);

        global::Darp.Luau.LuauReturn F(global::Darp.Luau.LuauArgs args)
        {
            if (!args.TryValidateArgumentCount(0, out string? error))
                return global::Darp.Luau.LuauReturn.Error(error);

            var returns = onLuaCall();
            return global::Darp.Luau.LuauReturn.Ok(returns);
        }
    }
    [global::System.Runtime.CompilerServices.InterceptsLocationAttribute(1, "ScrubbedInterceptLocation")]
    public static global::Darp.Luau.LuauFunction CreateMethod(this global::Darp.Luau.LuauState state, global::System.Func<string, string> onLuaCall)
    {
        global::System.ArgumentNullException.ThrowIfNull(state);
        global::System.ArgumentNullException.ThrowIfNull(onLuaCall);
        return state.CreateFunctionBuilder(F);

        global::Darp.Luau.LuauReturn F(global::Darp.Luau.LuauArgs args)
        {
            if (!args.TryValidateArgumentCount(1, out string? error))
                return global::Darp.Luau.LuauReturn.Error(error);
            if (!args.TryReadUtf8String(parameterIndex: 1, out global::System.ReadOnlySpan<byte> a1Raw, out error))
                return global::Darp.Luau.LuauReturn.Error(error);
            string a1 = global::System.Text.Encoding.UTF8.GetString(a1Raw);
            var returns = onLuaCall(a1);
            return global::Darp.Luau.LuauReturn.Ok(returns);
        }
    }
}
}

namespace System.Runtime.CompilerServices
{
    [global::System.Diagnostics.Conditional("DEBUG")]
    [AttributeUsage(AttributeTargets.Method, AllowMultiple = true)]
    file sealed class InterceptsLocationAttribute : Attribute
    {
        public InterceptsLocationAttribute(int version, string data)
        {
            _ = version;
            _ = data;
        }
    }
}
