//HintName: global__ArcadeLibrary.LuauLibrary.g.cs
// <auto-generated/>
#nullable enable

public static partial class ArcadeLibrary
{
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Darp.Luau.Generator", "GeneratorVersion")]
    public const string LuauLibraryName = "arcade";
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Darp.Luau.Generator", "GeneratorVersion")]
    public static void Register(global::Darp.Luau.LuauState lua)
    {
        global::System.ArgumentNullException.ThrowIfNull(lua);
        lua.OpenLibrary(LuauLibraryName, BuildLibrary);
        
        void BuildLibrary(global::Darp.Luau.LuauState state, in global::Darp.Luau.LuauTable lib)
        {
            using global::Darp.Luau.LuauFunction __var0 = state.CreateFunctionBuilder(args =>
            {
                if (!args.TryValidateArgumentCount(2, out string? error))
                    return global::Darp.Luau.LuauReturn.Error(error);
                if (!args.TryReadNumber(parameterIndex: 1, out double a1Raw, out error))
                    return global::Darp.Luau.LuauReturn.Error(error);
                int a1 = (int)a1Raw;
                if (!args.TryReadNumber(parameterIndex: 2, out double a2Raw, out error))
                    return global::Darp.Luau.LuauReturn.Error(error);
                int a2 = (int)a2Raw;
                var returns = AddScore(a1, a2);
                return global::Darp.Luau.LuauReturn.Ok(returns);
            });
            lib.Set("add_score", __var0);
            lib.Set("tokens", Tokens);
        }
    }
}
