//HintName: global__GuildLibrary.LuauLibrary.g.cs
// <auto-generated/>
#nullable enable

public sealed partial class GuildLibrary
{
    public const string LuauLibraryName = "guild";
    
    public void Register(global::Darp.Luau.LuauState lua)
    {
        global::System.ArgumentNullException.ThrowIfNull(lua);
        lua.OpenLibrary(LuauLibraryName, BuildLibrary);
        
        void BuildLibrary(global::Darp.Luau.LuauState state, in global::Darp.Luau.LuauTable lib)
        {
            using global::Darp.Luau.LuauTable __heroes = state.CreateTable();
            using global::Darp.Luau.LuauFunction __heroes_create = state.CreateFunctionBuilder(args =>
            {
                if (!args.TryValidateArgumentCount(1, out string? error))
                    return global::Darp.Luau.LuauReturn.Error(error);
                if (!args.TryReadUtf8String(parameterIndex: 1, out global::System.ReadOnlySpan<byte> a1Raw, out error))
                    return global::Darp.Luau.LuauReturn.Error(error);
                string a1 = global::System.Text.Encoding.UTF8.GetString(a1Raw);
                var returns = CreateHero(a1);
                return global::Darp.Luau.LuauReturn.Ok(global::Darp.Luau.IntoLuau.FromUserdata(returns));
            });
            __heroes.Set("create", __heroes_create);
            lib.Set("heroes", __heroes);
            
        }
    }
}
