//HintName: global__DemoLibrary.LuauLibrary.g.cs
// <auto-generated/>
#nullable enable

public static partial class DemoLibrary
{
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Darp.Luau.Generator", "GeneratorVersion")]
    public const string LuauLibraryName = "demo";
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Darp.Luau.Generator", "GeneratorVersion")]
    public static void Register(global::Darp.Luau.LuauState lua)
    {
        global::System.ArgumentNullException.ThrowIfNull(lua);
        lua.OpenLibrary(LuauLibraryName, BuildLibrary);
        
        void BuildLibrary(global::Darp.Luau.LuauState state, in global::Darp.Luau.LuauTable lib)
        {
            using global::Darp.Luau.LuauTable __var0 = state.CreateTable();
            using global::Darp.Luau.LuauFunction __var1 = state.CreateFunctionBuilder(args =>
            {
                if (!args.TryValidateArgumentCount(0, out string? error))
                    return global::Darp.Luau.LuauReturn.Error(error);
                var returns = One();
                return global::Darp.Luau.LuauReturn.Ok(returns);
            });
            __var0.Set("b_c", __var1);
            lib.Set("a", __var0);
            
            using global::Darp.Luau.LuauTable __var2 = state.CreateTable();
            using global::Darp.Luau.LuauFunction __var3 = state.CreateFunctionBuilder(args =>
            {
                if (!args.TryValidateArgumentCount(0, out string? error))
                    return global::Darp.Luau.LuauReturn.Error(error);
                var returns = Two();
                return global::Darp.Luau.LuauReturn.Ok(returns);
            });
            __var2.Set("c", __var3);
            lib.Set("a_b", __var2);
            
            using global::Darp.Luau.LuauFunction __var4 = state.CreateFunctionBuilder(args =>
            {
                if (!args.TryValidateArgumentCount(0, out string? error))
                    return global::Darp.Luau.LuauReturn.Error(error);
                var returns = FooBar();
                return global::Darp.Luau.LuauReturn.Ok(returns);
            });
            lib.Set("foo-bar", __var4);
            using global::Darp.Luau.LuauTable __var5 = state.CreateTable();
            using global::Darp.Luau.LuauFunction __var6 = state.CreateFunctionBuilder(args =>
            {
                if (!args.TryValidateArgumentCount(0, out string? error))
                    return global::Darp.Luau.LuauReturn.Error(error);
                var returns = CreateItem();
                return global::Darp.Luau.LuauReturn.Ok(returns);
            });
            __var5.Set("create item", __var6);
            lib.Set("tools", __var5);
            
        }
    }
}
