//HintName: CollisionLibrary.LuauLibrary.g.cs
// <auto-generated/>
#nullable enable

public static partial class CollisionLibrary
{
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Darp.Luau.Generator", "GeneratorVersion")]
    public const string LuauLibraryName = "collisions";
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Darp.Luau.Generator", "GeneratorVersion")]
    public static void Register(global::Darp.Luau.LuauState lua)
    {
        global::System.ArgumentNullException.ThrowIfNull(lua);
        lua.OpenLibrary(LuauLibraryName, BuildLibrary);
        
        void BuildLibrary(global::Darp.Luau.LuauState state, in global::Darp.Luau.LuauTable lib)
        {
            using global::Darp.Luau.LuauFunction __var0 = state.CreateFunctionBuilder(args =>
            {
                if (!args.TryValidateArgumentCount(0, out string? error))
                    return global::Darp.Luau.LuauReturn.Error(error);
                var returns = global::CollisionLibrary.returns();
                return global::Darp.Luau.LuauReturn.Ok(returns);
            });
            lib.Set("returns", __var0);
        }
    }
}
