//HintName: global__RecoverableLibrary.LuauLibrary.g.cs
// <auto-generated/>
#nullable enable

public sealed partial class RecoverableLibrary
{
    public const string LuauLibraryName = "recoverable";
    
    public void Register(global::Darp.Luau.LuauState lua)
    {
        global::System.ArgumentNullException.ThrowIfNull(lua);
        lua.OpenLibrary(LuauLibraryName, BuildLibrary);
        
        void BuildLibrary(global::Darp.Luau.LuauState state, in global::Darp.Luau.LuauTable lib)
        {
            using global::Darp.Luau.LuauFunction __var0 = state.CreateFunctionBuilder(args =>
            {
                if (!args.TryValidateArgumentCount(0, out string? error))
                    return global::Darp.Luau.LuauReturn.Error(error);
                var returns = CreateField();
                return global::Darp.Luau.LuauReturn.Ok(returns);
            });
            lib.Set("Field", __var0);
            using global::Darp.Luau.LuauFunction __var1 = state.CreateFunctionBuilder(args =>
            {
                if (!args.TryValidateArgumentCount(0, out string? error))
                    return global::Darp.Luau.LuauReturn.Error(error);
                var returns = DuplicateOne();
                return global::Darp.Luau.LuauReturn.Ok(returns);
            });
            lib.Set("duplicate", __var1);
            using global::Darp.Luau.LuauFunction __var2 = state.CreateFunctionBuilder(args =>
            {
                if (!args.TryValidateArgumentCount(0, out string? error))
                    return global::Darp.Luau.LuauReturn.Error(error);
                var returns = Ok();
                return global::Darp.Luau.LuauReturn.Ok(returns);
            });
            lib.Set("ok", __var2);
        }
    }
}
