using System.CodeDom.Compiler;
using System.Collections.Immutable;
using System.Diagnostics.CodeAnalysis;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Operations;

namespace Darp.Luau.Generator;

internal enum LuauValueType
{
    String,
}

internal static class CreateFunctionInterceptorsEmitter
{
    public static bool TryEmit(
        ImmutableArray<IInvocationOperation> calls,
        [NotNullWhen(true)] out string? source,
        out List<Diagnostic> diagnostics
    )
    {
        using var stringWriter = new StringWriter();
        using var writer = new IndentedTextWriter(stringWriter);
        diagnostics = [];

        List<InvocationMethodData> datas = [];
        foreach (IInvocationOperation calledMethod in calls)
        {
            var syntax = (InvocationExpressionSyntax)calledMethod.Syntax;
            InterceptableLocation? location = calledMethod.SemanticModel.GetInterceptableLocation(syntax);
            if (location is null)
                continue;
            datas.Add(
                new InvocationMethodData(
                    location.Version,
                    location.Data,
                    [LuauValueType.String],
                    [LuauValueType.String]
                )
            );
        }

        if (datas.Count == 0)
        {
            source = null;
            return false;
        }
        // TODO: Filter out duplicate parameter sets

        writer.WriteMultiLine(
            """
            // <auto-generated/>
            #nullable enable

            namespace Darp.Luau.Generator
            {
            file static class CreateFunctionInterceptors
            {
            """
        );
        writer.Indent++;
        foreach (InvocationMethodData data in datas)
        {
            writer.WriteMultiLine(
                $$"""
                [global::System.Runtime.CompilerServices.InterceptsLocationAttribute({{data.InterceptorLocationVersion}}, "{{data.InterceptorLocationData}}")]
                public static global::Darp.Luau.LuauFunction CreateMethod(this global::Darp.Luau.LuauState state, global::System.Action onLuaCall)
                {
                    global::System.ArgumentNullException.ThrowIfNull(state);
                    global::System.ArgumentNullException.ThrowIfNull(onLuaCall);
                    return state.CreateFunction(F);
                    
                    void F(LuauFunctions x)
                    {
                        global::System.ArgumentOutOfRangeException.ThrowIfNotEqual(x.NumberOfParameters, 0);
                        onLuaCall();
                    }
                }
                """
            );
        }

        writer.Indent--;
        writer.WriteLine("}");
        writer.WriteLine("}");
        writer.WriteLine();
        writer.WriteMultiLine(
            """
            namespace System.Runtime.CompilerServices
            {
                [AttributeUsage(AttributeTargets.Method, AllowMultiple = true)]
                public class InterceptsLocationAttribute : Attribute
                {
                    public InterceptsLocationAttribute(int version, string data) { }
                }
            }
            """
        );
        source = stringWriter.ToString();
        return true;
    }
}

internal sealed record InvocationMethodData(
    int InterceptorLocationVersion,
    string InterceptorLocationData,
    ImmutableArray<LuauValueType> Parameters,
    ImmutableArray<LuauValueType> ReturnParameters
);
