using System.CodeDom.Compiler;
using System.Diagnostics.CodeAnalysis;
using Darp.Luau.Generator.GeneratedExports;
using Darp.Luau.Generator.Helpers;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Darp.Luau.Generator;

internal static class GeneratedLibraryExportsEmitter
{
    public static bool TryEmit(
        INamedTypeSymbol type,
        GeneratedExportSurfaceIr model,
        [NotNullWhen(true)] out string? source,
        out List<Diagnostic> diagnostics
    )
    {
        diagnostics = [];
        if (model.LibraryRoot is null || string.IsNullOrWhiteSpace(model.LibraryName))
        {
            source = null;
            return false;
        }

        if (TryFindGeneratedOnlyUserdataUsage(model.LibraryRoot, out string? memberName, out string? typeName))
        {
            diagnostics.Add(
                Diagnostic.Create(
                    DiagnosticDescriptors.InvalidGeneratedExportShapeDescriptor,
                    GeneratedExportsCompilationContext.GetSymbolLocation(type),
                    $"library member '{memberName}' uses generated userdata type '{typeName}', which requires userdata code generation that is not emitted in this step"
                )
            );
            source = null;
            return false;
        }

        using var stringWriter = new StringWriter();
        using var writer = new IndentedTextWriter(stringWriter);
        WriteFile(writer, type, model);
        source = stringWriter.ToString();
        return true;
    }

    private static bool TryFindGeneratedOnlyUserdataUsage(
        GeneratedLibraryExportNodeIr node,
        [NotNullWhen(true)] out string? memberName,
        [NotNullWhen(true)] out string? typeName
    )
    {
        if (node.Member is GeneratedExportPropertyIr property)
        {
            if (
                property.Getter is
                {
                    Type: { IsGeneratedUserdata: true, OriginalTypeName: { } propertyTypeName }
                }
            )
            {
                memberName = property.LuauName;
                typeName = propertyTypeName;
                return true;
            }

            if (
                property.Setter is
                {
                    Type: { IsGeneratedUserdata: true, OriginalTypeName: { } setterTypeName }
                }
            )
            {
                memberName = property.LuauName;
                typeName = setterTypeName;
                return true;
            }
        }
        else if (node.Member is GeneratedExportMethodIr method)
        {
            foreach (LuauTypeMapping parameter in method.Parameters)
            {
                if (parameter is { IsGeneratedUserdata: true, OriginalTypeName: { } parameterTypeName })
                {
                    memberName = method.LuauName;
                    typeName = parameterTypeName;
                    return true;
                }
            }

            foreach (LuauTypeMapping returnType in method.ReturnTypes)
            {
                if (returnType is { IsGeneratedUserdata: true, OriginalTypeName: { } returnTypeName })
                {
                    memberName = method.LuauName;
                    typeName = returnTypeName;
                    return true;
                }
            }
        }

        foreach (GeneratedLibraryExportNodeIr child in node.Children)
        {
            if (TryFindGeneratedOnlyUserdataUsage(child, out memberName, out typeName))
                return true;
        }

        memberName = null;
        typeName = null;
        return false;
    }

    private static void WriteFile(IndentedTextWriter writer, INamedTypeSymbol type, GeneratedExportSurfaceIr model)
    {
        writer.WriteLine("// <auto-generated/>");
        writer.WriteLine("#nullable enable");
        writer.WriteLine();

        if (!type.ContainingNamespace.IsGlobalNamespace)
        {
            writer.WriteLine($"namespace {type.ContainingNamespace.ToDisplayString()}");
            writer.WriteLine("{");
            writer.Indent++;
        }

        writer.WriteLine(GetTypeDeclaration(type));
        writer.WriteLine("{");
        writer.Indent++;
        writer.WriteLine($"public const string LuauLibraryName = {SymbolDisplay.FormatLiteral(model.LibraryName!, quote: true)};");
        writer.WriteLine();
        writer.WriteLine($"public {GetRegisterModifier(type)}void Register(global::Darp.Luau.LuauState lua)");
        writer.WriteLine("{");
        writer.Indent++;
        writer.WriteLine("global::System.ArgumentNullException.ThrowIfNull(lua);");
        writer.WriteLine("lua.OpenLibrary(LuauLibraryName, BuildLibrary);");
        writer.WriteLine();
        writer.WriteLine("void BuildLibrary(global::Darp.Luau.LuauState state, in global::Darp.Luau.LuauTable lib)");
        writer.WriteLine("{");
        writer.Indent++;
        WriteLibraryNodeContents(writer, model.LibraryRoot!, "lib", []);
        writer.Indent--;
        writer.WriteLine("}");
        writer.Indent--;
        writer.WriteLine("}");
        writer.Indent--;
        writer.WriteLine("}");

        if (!type.ContainingNamespace.IsGlobalNamespace)
        {
            writer.Indent--;
            writer.WriteLine("}");
        }
    }

    private static void WriteLibraryNodeContents(
        IndentedTextWriter writer,
        GeneratedLibraryExportNodeIr node,
        string tableVariableName,
        IReadOnlyList<string> pathSegments
    )
    {
        foreach (GeneratedLibraryExportNodeIr child in node.Children.OrderBy(static x => x.Name, StringComparer.Ordinal))
        {
            if (child.Member is null)
            {
                string nestedTableName = "__" + string.Join("_", pathSegments.Concat([child.Name]));
                writer.WriteLine($"using global::Darp.Luau.LuauTable {nestedTableName} = state.CreateTable();");
                WriteLibraryNodeContents(writer, child, nestedTableName, pathSegments.Concat([child.Name]).ToArray());
                writer.WriteLine($"{tableVariableName}.Set({SymbolDisplay.FormatLiteral(child.Name, quote: true)}, {nestedTableName});");
                writer.WriteLine();
                continue;
            }

            WriteMember(writer, child.Member, tableVariableName);
        }
    }

    private static void WriteMember(IndentedTextWriter writer, GeneratedExportMemberIr member, string tableVariableName)
    {
        switch (member)
        {
            case GeneratedExportPropertyIr property:
                WriteProperty(writer, property, tableVariableName);
                break;
            case GeneratedExportMethodIr method:
                WriteMethod(writer, method, tableVariableName);
                break;
            default:
                throw new InvalidOperationException($"Unsupported generated library member '{member.GetType().Name}'.");
        }
    }

    private static void WriteProperty(IndentedTextWriter writer, GeneratedExportPropertyIr property, string tableVariableName)
    {
        GeneratedExportAccessorIr accessor =
            property.Getter ?? throw new InvalidOperationException("Generated library properties must have a getter.");
        string keyLiteral = SymbolDisplay.FormatLiteral(property.PathSegments[^1], quote: true);
        writer.WriteLine($"{tableVariableName}.Set({keyLiteral}, {FormatIntoLuauExpression(property.ManagedName, accessor.Type)});");
    }

    private static void WriteMethod(IndentedTextWriter writer, GeneratedExportMethodIr method, string tableVariableName)
    {
        string functionVariableName = "__" + string.Join("_", method.PathSegments);
        string keyLiteral = SymbolDisplay.FormatLiteral(method.PathSegments[^1], quote: true);

        writer.WriteLine($"using global::Darp.Luau.LuauFunction {functionVariableName} = state.CreateFunctionBuilder(args =>");
        writer.WriteLine("{");
        writer.Indent++;
        writer.WriteLine($"if (!args.TryValidateArgumentCount({method.Parameters.Length}, out string? error))");
        writer.WriteLine("    return global::Darp.Luau.LuauReturn.Error(error);");

        for (int i = 0; i < method.Parameters.Length; i++)
            writer.WriteMultiLine(GenerateCheckParameter(i + 1, method.Parameters[i]));

        string callExpression =
            $"{method.ManagedName}({string.Join(", ", Enumerable.Range(1, method.Parameters.Length).Select(static i => $"a{i}"))})";
        if (method.ReturnTypes.Length == 0)
        {
            writer.WriteLine($"{callExpression};");
            writer.WriteLine("return global::Darp.Luau.LuauReturn.Ok();");
        }
        else
        {
            writer.WriteLine($"var returns = {callExpression};");
            if (method.ReturnTypes.Length == 1)
            {
                writer.WriteLine(
                    $"return global::Darp.Luau.LuauReturn.Ok({FormatIntoLuauExpression("returns", method.ReturnTypes[0])});"
                );
            }
            else
            {
                writer.WriteLine(
                    $"return global::Darp.Luau.LuauReturn.Ok({string.Join(", ", method.ReturnTypes.Select((x, i) => FormatIntoLuauExpression($"returns.Item{i + 1}", x)))});"
                );
            }
        }

        writer.Indent--;
        writer.WriteLine("});");
        writer.WriteLine($"{tableVariableName}.Set({keyLiteral}, {functionVariableName});");
    }

    private static string GenerateCheckParameter(int parameterIndex, LuauTypeMapping param)
    {
        string dotnetType = GetDotnetType(param);

        return param.Type switch
        {
            LuauValueType.Boolean => param.IsNullable
                ? $"""
                    if (!args.TryReadBooleanOrNil(parameterIndex: {parameterIndex}, out {dotnetType} a{parameterIndex}, out error))
                        return global::Darp.Luau.LuauReturn.Error(error);
                    """
                : $"""
                    if (!args.TryReadBoolean(parameterIndex: {parameterIndex}, out {dotnetType} a{parameterIndex}, out error))
                        return global::Darp.Luau.LuauReturn.Error(error);
                    """,
            LuauValueType.String => param.IsNullable
                ? $"""
                    if (!args.TryReadUtf8StringOrNil(parameterIndex: {parameterIndex}, out {dotnetType} a{parameterIndex}, out var isNil, out error))
                        return global::Darp.Luau.LuauReturn.Error(error);
                    """
                : $"""
                    if (!args.TryReadUtf8String(parameterIndex: {parameterIndex}, out {dotnetType} a{parameterIndex}, out error))
                        return global::Darp.Luau.LuauReturn.Error(error);
                    """,
            LuauValueType.StringCharSpan => $"""
                if (!args.TryReadUtf8String(parameterIndex: {parameterIndex}, out global::System.ReadOnlySpan<byte> a{parameterIndex}Raw, out error))
                    return global::Darp.Luau.LuauReturn.Error(error);
                global::System.Span<char> a{parameterIndex} = stackalloc char[global::System.Text.Encoding.UTF8.GetCharCount(a{parameterIndex}Raw)];
                _ = global::System.Text.Encoding.UTF8.GetChars(a{parameterIndex}Raw, a{parameterIndex});
                """,
            LuauValueType.StringString => param.IsNullable
                ? $"""
                    if (!args.TryReadUtf8StringOrNil(parameterIndex: {parameterIndex}, out global::System.ReadOnlySpan<byte> a{parameterIndex}Raw, out bool a{parameterIndex}IsNil, out error))
                        return global::Darp.Luau.LuauReturn.Error(error);
                    {dotnetType} a{parameterIndex} = a{parameterIndex}IsNil ? null : global::System.Text.Encoding.UTF8.GetString(a{parameterIndex}Raw);
                    """
                : $"""
                    if (!args.TryReadUtf8String(parameterIndex: {parameterIndex}, out global::System.ReadOnlySpan<byte> a{parameterIndex}Raw, out error))
                        return global::Darp.Luau.LuauReturn.Error(error);
                    string a{parameterIndex} = global::System.Text.Encoding.UTF8.GetString(a{parameterIndex}Raw);
                    """,
            LuauValueType.Number => param.IsNullable
                ? $"""
                    if (!args.TryReadNumberOrNil(parameterIndex: {parameterIndex}, out {dotnetType} a{parameterIndex}, out error))
                        return global::Darp.Luau.LuauReturn.Error(error);
                    """
                : $"""
                    if (!args.TryReadNumber(parameterIndex: {parameterIndex}, out {dotnetType} a{parameterIndex}, out error))
                        return global::Darp.Luau.LuauReturn.Error(error);
                    """,
            LuauValueType.NumberByte
            or LuauValueType.NumberUShort
            or LuauValueType.NumberUInt
            or LuauValueType.NumberULong
            or LuauValueType.NumberUInt128
            or LuauValueType.NumberSByte
            or LuauValueType.NumberShort
            or LuauValueType.NumberInt
            or LuauValueType.NumberLong
            or LuauValueType.NumberInt128
            or LuauValueType.NumberHalf
            or LuauValueType.NumberFloat
            or LuauValueType.NumberDecimal => param.IsNullable
                ? $"""
                    if (!args.TryReadNumberOrNil(parameterIndex: {parameterIndex}, out double? a{parameterIndex}Raw, out error))
                        return global::Darp.Luau.LuauReturn.Error(error);
                    {dotnetType} a{parameterIndex} = ({dotnetType})a{parameterIndex}Raw;
                    """
                : $"""
                    if (!args.TryReadNumber(parameterIndex: {parameterIndex}, out double a{parameterIndex}Raw, out error))
                        return global::Darp.Luau.LuauReturn.Error(error);
                    {dotnetType} a{parameterIndex} = ({dotnetType})a{parameterIndex}Raw;
                    """,
            LuauValueType.Enum => param.IsNullable
                ? $"""
                    if (!args.TryReadNumberOrNil(parameterIndex: {parameterIndex}, out double? a{parameterIndex}Raw, out error))
                        return global::Darp.Luau.LuauReturn.Error(error);
                    {dotnetType} a{parameterIndex} = a{parameterIndex}Raw.HasValue ? ({param.OriginalTypeName})a{parameterIndex}Raw.Value : null;
                    """
                : $"""
                    if (!args.TryReadNumber(parameterIndex: {parameterIndex}, out double a{parameterIndex}Raw, out error))
                        return global::Darp.Luau.LuauReturn.Error(error);
                    {dotnetType} a{parameterIndex} = ({param.OriginalTypeName})a{parameterIndex}Raw;
                    """,
            LuauValueType.ManagedUserdata => param.IsNullable
                ? $"""
                    if (!args.TryReadUserdataOrNil<{param.OriginalTypeName}>(parameterIndex: {parameterIndex}, out {dotnetType} a{parameterIndex}, out error))
                        return global::Darp.Luau.LuauReturn.Error(error);
                    """
                : $"""
                    if (!args.TryReadUserdata<{param.OriginalTypeName}>(parameterIndex: {parameterIndex}, out {dotnetType}? a{parameterIndex}, out error))
                        return global::Darp.Luau.LuauReturn.Error(error);
                    """,
            LuauValueType.LuauValue
            or LuauValueType.LuauTableView
            or LuauValueType.LuauStringView
            or LuauValueType.LuauFunctionView
            or LuauValueType.LuauBufferView
            or LuauValueType.LuauUserdataView =>
                $"""
                if (!args.{GetTryFunction(param.Type)}(parameterIndex: {parameterIndex}, out {dotnetType} a{parameterIndex}, out error))
                    return global::Darp.Luau.LuauReturn.Error(error);
                """,
            _ => throw new ArgumentOutOfRangeException(nameof(param), param.Type, "Could not generate parameter checks"),
        };
    }

    private static string GetTryFunction(LuauValueType type)
    {
        return type switch
        {
            LuauValueType.Boolean => "TryReadBoolean",
            LuauValueType.String or LuauValueType.StringCharSpan or LuauValueType.StringString => "TryReadUtf8String",
            LuauValueType.Number
            or LuauValueType.NumberByte
            or LuauValueType.NumberUShort
            or LuauValueType.NumberUInt
            or LuauValueType.NumberULong
            or LuauValueType.NumberUInt128
            or LuauValueType.NumberSByte
            or LuauValueType.NumberShort
            or LuauValueType.NumberInt
            or LuauValueType.NumberLong
            or LuauValueType.NumberInt128
            or LuauValueType.NumberHalf
            or LuauValueType.NumberFloat
            or LuauValueType.NumberDecimal
            or LuauValueType.Enum => "TryReadNumber",
            LuauValueType.LuauValue => "TryReadLuauValue",
            LuauValueType.LuauTableView => "TryReadLuauTable",
            LuauValueType.LuauFunctionView => "TryReadLuauFunction",
            LuauValueType.LuauStringView => "TryReadLuauString",
            LuauValueType.LuauBufferView => "TryReadLuauBuffer",
            LuauValueType.LuauUserdataView => "TryReadLuauUserdata",
            _ => throw new ArgumentOutOfRangeException(nameof(type), type, "Could not get the TryRead function"),
        };
    }

    private static string FormatIntoLuauExpression(string valueExpression, LuauTypeMapping mapping)
    {
        return mapping.Type switch
        {
            LuauValueType.NumberDecimal or LuauValueType.NumberUInt128 or LuauValueType.NumberInt128 => mapping.IsNullable
                ? $"(double?){valueExpression}"
                : $"(double){valueExpression}",
            LuauValueType.Enum => mapping.IsNullable ? $"(double?){valueExpression}" : $"(double){valueExpression}",
            LuauValueType.ManagedUserdata => mapping.IsNullable
                ? $"{valueExpression} is null ? default(global::Darp.Luau.IntoLuau) : global::Darp.Luau.IntoLuau.FromUserdata({valueExpression})"
                : $"global::Darp.Luau.IntoLuau.FromUserdata({valueExpression})",
            _ => valueExpression,
        };
    }

    private static string GetDotnetType(LuauTypeMapping param)
    {
        if (param is { Type: LuauValueType.Enum or LuauValueType.ManagedUserdata, OriginalTypeName: { } name })
            return param.IsNullable ? $"{name}?" : name;

        return EmitterHelper.GetDotnetType((param.Type, param.IsNullable));
    }

    private static string GetTypeDeclaration(INamedTypeSymbol type)
    {
        TypeDeclarationSyntax syntax = type.DeclaringSyntaxReferences
            .Select(static x => x.GetSyntax())
            .OfType<TypeDeclarationSyntax>()
            .First();

        string modifiers = string.Join(
            " ",
            syntax.Modifiers.Where(static x =>
                    x.IsKind(SyntaxKind.PublicKeyword)
                    || x.IsKind(SyntaxKind.InternalKeyword)
                    || x.IsKind(SyntaxKind.PrivateKeyword)
                    || x.IsKind(SyntaxKind.ProtectedKeyword)
                    || x.IsKind(SyntaxKind.StaticKeyword)
                    || x.IsKind(SyntaxKind.AbstractKeyword)
                    || x.IsKind(SyntaxKind.SealedKeyword)
                    || x.IsKind(SyntaxKind.PartialKeyword)
                )
                .Select(static x => x.Text)
        );

        return syntax switch
        {
            ClassDeclarationSyntax classDeclaration => $"{modifiers} class {classDeclaration.Identifier.Text}",
            StructDeclarationSyntax structDeclaration => $"{modifiers} struct {structDeclaration.Identifier.Text}",
            RecordDeclarationSyntax recordDeclaration => $"{modifiers} record {recordDeclaration.ClassOrStructKeyword.Text} {recordDeclaration.Identifier.Text}",
            _ => throw new InvalidOperationException($"Unsupported library type declaration '{syntax.Kind()}'."),
        };
    }

    private static string GetRegisterModifier(INamedTypeSymbol type) => type.IsStatic ? "static " : string.Empty;
}
