using System.CodeDom.Compiler;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Darp.Luau.Generator;

internal static class GeneratedExportsEmitterHelper
{
    public static void WriteFileHeader(IndentedTextWriter writer)
    {
        writer.WriteLine("// <auto-generated/>");
        writer.WriteLine("#nullable enable");
        writer.WriteLine();
    }

    public static bool WriteNamespaceStart(IndentedTextWriter writer, INamedTypeSymbol type)
    {
        if (type.ContainingNamespace.IsGlobalNamespace)
            return false;

        writer.WriteLine($"namespace {type.ContainingNamespace.ToDisplayString()}");
        writer.WriteLine("{");
        writer.Indent++;
        return true;
    }

    public static void WriteNamespaceEnd(IndentedTextWriter writer, bool hasNamespace)
    {
        if (!hasNamespace)
            return;

        writer.Indent--;
        writer.WriteLine("}");
    }

    public static string GetTypeDeclaration(INamedTypeSymbol type, string? baseList = null)
    {
        TypeDeclarationSyntax syntax = type.DeclaringSyntaxReferences
            .Select(static x => x.GetSyntax())
            .OfType<TypeDeclarationSyntax>()
            .First();

        string modifiers = string.Join(
            " ",
            syntax.Modifiers.Where(static x =>
                    x.IsKind(SyntaxKind.PublicKeyword)
                    || x.IsKind(SyntaxKind.InternalKeyword)
                    || x.IsKind(SyntaxKind.PrivateKeyword)
                    || x.IsKind(SyntaxKind.ProtectedKeyword)
                    || x.IsKind(SyntaxKind.StaticKeyword)
                    || x.IsKind(SyntaxKind.AbstractKeyword)
                    || x.IsKind(SyntaxKind.SealedKeyword)
                    || x.IsKind(SyntaxKind.PartialKeyword)
                )
                .Select(static x => x.Text)
        );
        string suffix = string.IsNullOrWhiteSpace(baseList) ? string.Empty : $" : {baseList}";

        return syntax switch
        {
            ClassDeclarationSyntax classDeclaration => $"{modifiers} class {classDeclaration.Identifier.Text}{suffix}",
            StructDeclarationSyntax structDeclaration => $"{modifiers} struct {structDeclaration.Identifier.Text}{suffix}",
            RecordDeclarationSyntax recordDeclaration =>
                $"{modifiers} record {recordDeclaration.ClassOrStructKeyword.Text} {recordDeclaration.Identifier.Text}{suffix}",
            _ => throw new InvalidOperationException($"Unsupported generated export type declaration '{syntax.Kind()}'."),
        };
    }

    public sealed class LocalNameAllocator
    {
        private int _next;

        public string Next() => $"__var{_next++}";
    }
}
