//HintName: global__Character.LuauUserdata.g.cs
// <auto-generated/>
#nullable enable

public sealed partial class Character : global::Darp.Luau.ILuauUserData<global::Character>
{
    public static global::Darp.Luau.LuauReturnSingle OnIndex(global::Character self, in global::Darp.Luau.LuauState state, in global::System.ReadOnlySpan<char> fieldName)
    {
        return fieldName switch
        {
            "kind" => global::Darp.Luau.LuauReturnSingle.Ok((double)self.Kind),
            "name" => global::Darp.Luau.LuauReturnSingle.Ok(self.Name),
            "score" => global::Darp.Luau.LuauReturnSingle.Ok(self.Score),
            "secret" => global::Darp.Luau.LuauReturnSingle.Error("userdata member 'secret' is write-only"),
            _ => global::Darp.Luau.LuauReturnSingle.NotHandled,
        };
    }
    
    public static global::Darp.Luau.LuauOutcome OnSetIndex(global::Character self, global::Darp.Luau.LuauArgsSingle args, in global::System.ReadOnlySpan<char> fieldName)
    {
        switch (fieldName)
        {
            case "kind":
            {
                if (!args.TryReadNumber(out double valueRaw, out string? error))
                    return global::Darp.Luau.LuauOutcome.Error(error);
                global::CharacterKind value = (global::CharacterKind)valueRaw;
                self.Kind = value;
                return global::Darp.Luau.LuauOutcome.Ok();
            }
            case "name":
            {
                if (!args.TryReadUtf8String(out string? value, out string? error))
                    return global::Darp.Luau.LuauOutcome.Error(error);
                self.Name = value;
                return global::Darp.Luau.LuauOutcome.Ok();
            }
            case "score":
            {
                return global::Darp.Luau.LuauOutcome.Error("userdata member 'score' is read-only");
            }
            case "secret":
            {
                if (!args.TryReadUtf8StringOrNil(out string? value, out string? error))
                    return global::Darp.Luau.LuauOutcome.Error(error);
                self.Secret = value;
                return global::Darp.Luau.LuauOutcome.Ok();
            }
            default:
                return global::Darp.Luau.LuauOutcome.NotHandledError;
        }
    }
    
    public static global::Darp.Luau.LuauReturn OnMethodCall(global::Character self, global::Darp.Luau.LuauArgs args, in global::System.ReadOnlySpan<char> methodName)
    {
        switch (methodName)
        {
            case "rename":
            {
                if (!args.TryValidateArgumentCount(2, out string? error))
                    return global::Darp.Luau.LuauReturn.Error(error);
                if (!args.TryReadUtf8String(parameterIndex: 1, out global::System.ReadOnlySpan<byte> a1Raw, out error))
                    return global::Darp.Luau.LuauReturn.Error(error);
                string a1 = global::System.Text.Encoding.UTF8.GetString(a1Raw);
                if (!args.TryReadNumber(parameterIndex: 2, out double a2Raw, out error))
                    return global::Darp.Luau.LuauReturn.Error(error);
                int a2 = (int)a2Raw;
                var returns = self.Rename(a1, a2);
                return global::Darp.Luau.LuauReturn.Ok(returns.Item1, returns.Item2);
            }
            case "reset":
            {
                if (!args.TryValidateArgumentCount(0, out string? error))
                    return global::Darp.Luau.LuauReturn.Error(error);
                self.Reset();
                return global::Darp.Luau.LuauReturn.Ok();
            }
            default:
                return global::Darp.Luau.LuauReturn.NotHandledError;
        }
    }
}
