//HintName: HeroCard.LuauUserdata.g.cs
// <auto-generated/>
#nullable enable

public sealed partial class HeroCard : global::Darp.Luau.ILuauUserData<global::HeroCard>
{
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Darp.Luau.Generator", "GeneratorVersion")]
    public static global::Darp.Luau.LuauReturnSingle OnIndex(global::HeroCard self, in global::Darp.Luau.LuauState state, in global::System.ReadOnlySpan<char> fieldName)
    {
        return fieldName switch
        {
            "name" => global::Darp.Luau.LuauReturnSingle.Ok(self.Name),
            _ => global::Darp.Luau.LuauReturnSingle.NotHandled,
        };
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Darp.Luau.Generator", "GeneratorVersion")]
    public static global::Darp.Luau.LuauOutcome OnSetIndex(global::HeroCard self, global::Darp.Luau.LuauArgsSingle args, in global::System.ReadOnlySpan<char> fieldName)
    {
        switch (fieldName)
        {
            case "name":
            {
                if (!args.TryReadUtf8String(out string? value, out string? error))
                    return global::Darp.Luau.LuauOutcome.Error(error);
                self.Name = value;
                return global::Darp.Luau.LuauOutcome.Ok();
            }
            default:
                return global::Darp.Luau.LuauOutcome.NotHandledError;
        }
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Darp.Luau.Generator", "GeneratorVersion")]
    public static global::Darp.Luau.LuauReturn OnMethodCall(global::HeroCard self, global::Darp.Luau.LuauArgs args, in global::System.ReadOnlySpan<char> methodName) => global::Darp.Luau.LuauReturn.NotHandledError;
}
