//HintName: global__GuildLibrary.LuauLibrary.g.cs
// <auto-generated/>
#nullable enable

public static partial class GuildLibrary
{
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Darp.Luau.Generator", "GeneratorVersion")]
    public const string LuauLibraryName = "guild";
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Darp.Luau.Generator", "GeneratorVersion")]
    public static void Register(global::Darp.Luau.LuauState lua)
    {
        global::System.ArgumentNullException.ThrowIfNull(lua);
        lua.OpenLibrary(LuauLibraryName, BuildLibrary);
        
        void BuildLibrary(global::Darp.Luau.LuauState state, in global::Darp.Luau.LuauTable lib)
        {
            using global::Darp.Luau.LuauTable __var0 = state.CreateTable();
            using global::Darp.Luau.LuauFunction __var1 = state.CreateFunctionBuilder(args =>
            {
                if (!args.TryValidateArgumentCount(1, out string? error))
                    return global::Darp.Luau.LuauReturn.Error(error);
                if (!args.TryReadUtf8String(parameterIndex: 1, out global::System.ReadOnlySpan<byte> a1Raw, out error))
                    return global::Darp.Luau.LuauReturn.Error(error);
                string a1 = global::System.Text.Encoding.UTF8.GetString(a1Raw);
                var returns = CreateHero(a1);
                return global::Darp.Luau.LuauReturn.Ok(global::Darp.Luau.IntoLuau.FromUserdata(returns));
            });
            __var0.Set("create", __var1);
            using global::Darp.Luau.LuauFunction __var2 = state.CreateFunctionBuilder(args =>
            {
                if (!args.TryValidateArgumentCount(2, out string? error))
                    return global::Darp.Luau.LuauReturn.Error(error);
                if (!args.TryReadUserdata<global::HeroCard>(parameterIndex: 1, out global::HeroCard? a1, out error))
                    return global::Darp.Luau.LuauReturn.Error(error);
                if (!args.TryReadUtf8String(parameterIndex: 2, out global::System.ReadOnlySpan<byte> a2Raw, out error))
                    return global::Darp.Luau.LuauReturn.Error(error);
                string a2 = global::System.Text.Encoding.UTF8.GetString(a2Raw);
                RenameHero(a1, a2);
                return global::Darp.Luau.LuauReturn.Ok();
            });
            __var0.Set("rename", __var2);
            lib.Set("heroes", __var0);
            
        }
    }
}
