name: Build and test .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Setup .NET
        uses: actions/setup-dotnet@v5

      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Test
        run: |
          dotnet test --no-build --verbosity normal \
            --collect:"XPlat Code Coverage;Format=cobertura" \
            --results-directory ./coverage-results

      - name: Attach code-coverage comment
        uses: rosslight/pr-code-coverage-visualizer@v2.2.0
        with:
          files: |
            coverage-results/**/coverage.cobertura.xml
          update-comment: true
          show-changed-lines-only: true

  warnings-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Setup .NET
        uses: actions/setup-dotnet@v5

      - name: Build warning-free Debug
        run: dotnet build "Darp.Lua.Net.slnx" -c Debug /warnaserror
      - name: Build warning-free Release
        run: dotnet build "Darp.Lua.Net.slnx" -c Release /warnaserror

  test-other-platforms:
    strategy:
      matrix:
        include:
          - name: Windows x64
            os: windows-latest
          - name: Windows arm64
            os: windows-11-arm
          - name: macOS x64
            os: macos-26-intel
          - name: macOS arm64
            os: macos-26
          - name: Linux arm64
            os: ubuntu-24.04-arm
    name: Test on ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v6
      - name: Setup .NET
        uses: actions/setup-dotnet@v5

      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Test
        run: dotnet test --no-build --verbosity normal
